name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Setup env
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # Install dependencies
      - name: Install local MJML
        run: yarn add mjml@3

      - name: Install gems
        run: bundle install
      # Run tests
      - name: Run tests
        run: bundle exec rake
